#
# Application
#

# Check Vault - TTS Google Credentials
liferay.learn.google.credentials=

# Check Vault - Training Importer
liferay.learn.webassessor.security.token=

#
# LXC
# Uncomment to deploy towards PROD, UAT, or DEV
#

## PROD
## liferay.learn.dxp.site.group.id=23484947
## com.liferay.lxc.dxp.domains=learn.liferay.com
## com.liferay.lxc.dxp.mainDomain=learn.liferay.com
## com.liferay.lxc.dxp.server.protocol=https

## UAT
## liferay.learn.dxp.site.group.id=32483059
## com.liferay.lxc.dxp.domains=learn-uat.liferay.com
## com.liferay.lxc.dxp.mainDomain=learn-uat.liferay.com
## com.liferay.lxc.dxp.server.protocol=https

## DEV
## liferay.learn.dxp.site.group.id=32484264
## com.liferay.lxc.dxp.domains=learn-dev.liferay.com
## com.liferay.lxc.dxp.mainDomain=learn-dev.liferay.com
## com.liferay.lxc.dxp.server.protocol=https

#
# OAuth
# Control Panel -> OAuth 2 Administration
#

liferay-learn-etc-spring-boot-oahs.oauth2.headless.server.client.secret=secret-e2e5fdd1-dddd-d9be-5698-333b966e76b

liferay.oauth.application.external.reference.codes=\
    liferay-learn-etc-spring-boot-oahs,\
    liferay-learn-etc-spring-boot-oaua

liferay.oauth.urls.excludes=\
    /learn/*\/questions,\
    /learn/*\/result,\
    /learn/lesson/*\/audio/base64,\
    /rag/search,\
    /ready

#
# Spring Boot
#

server.port=58081
