server.port=58090

playground.site.initializer.key=liferay-dotcom-playground-site-initializer
playground.site.administrator.role=Site Administrator
playground.quota.documents.bytes=104857600
playground.quota.pages=20
playground.quota.articles=20
